[workspace]
members = [
	"airtable",
	"barcodey",
	"checkr",
	"cfcert",
	"cio",
	"diesel-sentry",
	"docusign",
	"google-geocode",
	"macros",
	"mailchimp",
	"printy",
	"quickbooks",
	"shippo",
	"slack",
	"tailscale",
	"webhooky",
]
