[package]
name = "zoom-api"
description = "An API client for Zoom"
version = "0.1.4"
authors = ["Jess Frazelle <jess@oxide.computer>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/oxidecomputer/cio"
documentation = "https://docs.rs/zoom-api"

[dependencies]
chrono = "0.4"
cio-api = { path = "../cio" }
jsonwebtoken = "7"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
