name: docker-image-cio
on:
  pull_request:
    paths:
      - '**.rs'
      - '*/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/docker-image-cio.yml
      - rust-toolchain
      - '*/Dockerfile'
  push:
    branches: master
    paths:
      - '**.rs'
      - '*/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/docker-image-cio.yml
      - rust-toolchain
      - '*/Dockerfile'
  workflow_dispatch:
    inputs:
concurrency:
  group: docker-image-cio-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cio-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-cio-master
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push - cio
        uses: docker/build-push-action@v2
        with:
          push: ${{ ! startsWith(github.ref, 'refs/heads/dependabot') && github.event_name != 'pull_request' }}
          file: ./cio/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/cio:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
