name: docker-image
on:
  push:
    branches: master
    paths:
      - '**.rs'
      - '*/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/docker-image.yml
      - rust-toolchain
      - '*/Dockerfile'
jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push - cfcert
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./cfcert/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/cio:cfcert
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Build and push - webhooky
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./webhooky/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/cio:webhooky
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Build and push - cio
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./cio/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/cio:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
