name: docker-image-cfcert
on:
  pull_request:
    paths:
      - 'cfcert/**.rs'
      - 'cfcert/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/docker-image-cfcert.yml
      - rust-toolchain
      - 'cfcert/Dockerfile'
  push:
    branches: master
    paths:
      - 'cfcert/**.rs'
      - 'cfcert/Cargo.toml'
      - 'Cargo.lock'
      - .github/workflows/docker-image-cfcert.yml
      - rust-toolchain
      - 'cfcert/Dockerfile'
  workflow_dispatch:
    inputs:
concurrency:
  group: docker-image-cfcert-${{ github.ref }}
  cancel-in-progress: true
jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cleanup unused space
        shell: bash
        run: |
          set -x
          df -h /
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/microsoft
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/lib/jvm
          sudo rm -rf /usr/local/graalvm
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/swift
          df -h /
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-cfcert-${{ github.ref }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-cfcert-master
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push - cfcert
        uses: docker/build-push-action@v3
        with:
          push: ${{ ! startsWith(github.ref, 'refs/heads/dependabot') && github.event_name != 'pull_request' }}
          file: ./cfcert/Dockerfile
          tags: ghcr.io/${{ github.repository_owner }}/cio:cfcert
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      - name: Report remaining disk
        shell: bash
        run: |
          set -x
          df -h /
