on:
  push:
    paths:
    - 'scripts/**'
    - '.github/workflows/shellcheck.yml'
    - 'Makefile'
name: make shellcheck
jobs:
  shellcheck:
    name: make shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: make shellcheck
        run: make shellcheck
        shell: bash
